import type { ThemeKey } from "./profile";
import synced from "./publications.auto.json";

export type PublicationCategory = "journal" | "conference" | "preprint" | "patent";

export interface Publication {
  title: string;
  authors: string;
  venue: string;
  venueShort: string;
  year: number;
  category: PublicationCategory;
  theme: ThemeKey;
  link?: string;
  short?: string;
  note?: string;
  highlight?: string;
}

type Override = Partial<Publication> & { hidden?: boolean };

/*
 * Manual corrections. They always win over publications.auto.json, which is regenerated by
 * `npm run sync:pubs` (and weekly by GitHub Actions). Key each entry by DOI, arXiv id or the
 * exact title; set `hidden: true` to drop a paper from the site.
 */
export const overrides: Record<string, Override> = {
  "10.1016/j.neucom.2026.134277": {
    short: "Circular quasiconformal deturbulence",
    link: "https://www.sciencedirect.com/science/article/pii/S0925231226016759"
  },
  "10.1109/ICASSP55912.2026.11460905": {
    short: "LamiGauss",
    theme: "inverse",
    link: "https://ieeexplore.ieee.org/abstract/document/11460905"
  },
  "10.1109/TBME.2025.3574238": {
    short: "LINR CEST mapping",
    highlight: "Feature Article"
  },
  "10.1007/978-3-032-04947-6_8": {
    short: "Blind ultrasound video restoration",
    theme: "inverse",
    link: "https://link.springer.com/chapter/10.1007/978-3-032-04947-6_8"
  },
  "10.1109/ISBI56570.2024.10635440": {
    short: "Implicit subspace regression for CEST",
    authors: "Chu Chen; Yang Liu; Se Weon Park; Jizhou Li; Kannie W. Y. Chan; Raymond H. Chan"
  },
  "10.3390/jmse14040351": {
    short: "SEAF-Net"
  }
};

/* Items the sync cannot find, such as patents. */
const manual: Publication[] = [
  {
    title: "An unsupervised denoising method for LiDAR point clouds corrupted by snow particles",
    authors: "Inventors: Chu Chen; Junjie Cao",
    venue: "Patent CN114926356A",
    venueShort: "Patent",
    year: 2024,
    category: "patent",
    theme: "geometry"
  }
];

interface SyncedPublication extends Publication {
  id: string;
  aliases: string[];
}

const aliasOf = (key: string) => {
  const k = key.trim();
  if (/^10\.\d{4,}\//.test(k)) return `doi:${k.toLowerCase()}`;
  if (/^\d{4}\.\d{4,5}(v\d+)?$/.test(k)) return `arxiv:${k.replace(/v\d+$/, "")}`;
  return `title:${k.toLowerCase().replace(/[^a-z0-9]/g, "")}`;
};

const overrideByAlias = new Map(Object.entries(overrides).map(([key, value]) => [aliasOf(key), value]));

const applyOverrides = ({ id: _id, aliases, ...pub }: SyncedPublication) => {
  const override = aliases.map((a) => overrideByAlias.get(a)).find(Boolean) ?? {};
  return { ...pub, ...override };
};

export const publications: Publication[] = [
  ...(synced as SyncedPublication[]).map(applyOverrides).filter((p) => !p.hidden),
  ...manual
];

const SELF = ["chu chen", "chen, chu"];

export const isSelf = (name: string) => SELF.includes(name.trim().toLowerCase());

export const isFirstAuthor = (authors: string) => {
  const first = authors.replace(/^Inventors:\s*/i, "").split(";")[0] ?? "";
  return isSelf(first);
};

export const splitAuthors = (authors: string) =>
  authors
    .replace(/^Inventors:\s*/i, "")
    .split(";")
    .map((name) => name.trim())
    .filter(Boolean);

export const byYearDesc = (a: Publication, b: Publication) => b.year - a.year;
